import 'package:fpdart/fpdart.dart';
import 'package:lost_and_found/core/errors/failures.dart';
import 'package:lost_and_found/core/errors/exceptions.dart';
import 'package:lost_and_found/features/report/domain/entities/report.dart';
import 'package:lost_and_found/features/report/domain/repositories/report_repository.dart';
import 'package:lost_and_found/features/report/data/datasources/report_remote_datasource.dart';
import 'package:lost_and_found/features/report/data/models/report_dto.dart';

class ReportRepositoryImpl implements ReportRepository {
  final ReportRemoteDatasource _remoteDatasource;

  ReportRepositoryImpl(this._remoteDatasource);

  @override
  Future<Either<Failure, Report>> submitReport({
    required String userId,
    required String userName,
    required ReportCategory category,
    required String description,
    required String lostLocation,
    required DateTime lostDate,
  }) async {
    try {
      final reportDto = ReportDTO(
        id: '', // Generated by datasource
        trackId: '', // Generated by datasource
        userId: userId,
        userName: userName,
        category: category.name,
        description: description,
        lostLocation: lostLocation,
        lostDate: lostDate,
        status: ReportStatus.pending.name,
        createdAt: DateTime.now(),
        lastUpdatedAt: DateTime.now(),
      );

      final result = await _remoteDatasource.submitReport(reportDto);
      return right(result.toDomain());
    } on ServerException catch (e) {
      return left(ServerFailure(e.message));
    } catch (e) {
      return left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<Report>>> getMyReports(String userId) async {
    try {
      final dtos = await _remoteDatasource.getMyReports(userId);
      return right(dtos.map((dto) => dto.toDomain()).toList());
    } on ServerException catch (e) {
      return left(ServerFailure(e.message));
    } catch (e) {
      return left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Report>> getReportById(String reportId) async {
    try {
      final dto = await _remoteDatasource.getReportById(reportId);
      return right(dto.toDomain());
    } on NotFoundException catch (e) {
      return left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return left(ServerFailure(e.message));
    } catch (e) {
      return left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, Report>> getReportByTrackId(String trackId) async {
    try {
      final dto = await _remoteDatasource.getReportByTrackId(trackId);
      return right(dto.toDomain());
    } on NotFoundException catch (e) {
      return left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return left(ServerFailure(e.message));
    } catch (e) {
      return left(ServerFailure(e.toString()));
    }
  }

  @override
  Stream<Report> watchReport(String reportId) {
    return _remoteDatasource.watchReport(reportId).map((dto) => dto.toDomain());
  }
}
